### ISSUE TITLE
main.js引入css文件报错

### ISSUE THREAD

**Issue by 501981732** [xiaoiver/skeleton-demo#1]
如果在main.js 里面 import 'reset.css'
开发环境没问题
但是打包时会报错

`ERROR in ./src/assets/css/reset.css
Module build failed: EntryModuleNotFoundError: Entry module not found: Error: Can't find options with ident 'ref--5-2'
    at moduleFactory.create (/Users/wangmeng/Desktop/koa/easy-vue/node_modules/webpack/lib/Compilation.js:417:30)
    at factory (/Users/wangmeng/Desktop/koa/easy-vue/node_modules/webpack/lib/NormalModuleFactory.js:237:20)...`

**Comment by ChenShiChao** [comment]
+1，会导致引入第三方的CSS打包失败

**Comment by 501981732** [comment]
> +1，会导致引入第三方的CSS打包失败

不过貌似不影响打包结果

**Comment by leetia316** [comment]
遇到同样的问题，你们最终解决了吗？ @501981732 @ChenShiChao

**Comment by leetia316** [comment]
我最终解决了，解决方法如下： 
webpack.skeleton.conf.js
![image](https://user-images.githubusercontent.com/12868906/58763716-54256600-8591-11e9-9431-3779789137b8.png)

vue-loader.conf.js
![image](https://user-images.githubusercontent.com/12868906/58763728-76b77f00-8591-11e9-9ca3-5084bd077bb9.png)

webpack.dev.conf.js
dev参照prod的config.js配置，加入ExtractTextPlugin插件即可：
![image](https://user-images.githubusercontent.com/12868906/58763741-9babf200-8591-11e9-8e03-1c12f1bfe6f7.png)
![image](https://user-images.githubusercontent.com/12868906/58763745-aa92a480-8591-11e9-89be-d2fca73a0678.png)

**Comment by bandow** [comment]
是否可以支持不同页面对应的不同样式的骨架屏幕呢？
